#ifndef NOISE_H
#define NOISE_H

#include<opencv2/opencv.hpp>
#include<string>
#include <iterator>
#include <random>

using namespace std;
using namespace cv;
//NoiseRange can be modified for larger noise values in unoform noise
#define NoiseRange 50
// function to return a random number between -NoiseRange/2 and NoiseRange/2
int GenUniformNoise();
//function to return a random number between 0 and 100
int GenRandProb();
//function to add a uniform noise value generated by GenUniformNoise funtion to all pixels in the Matrix and return a the Matrix object
Mat UniformNoise(Mat src);
//function to add gaussian noise which has normal distribution , mean = 0 and standard deviation = 20 
Mat GaussianNoise(Mat src);
//function to add salt pepper noise to image and return the new Matrix object
//the amount of the noise can be controlled by modifiying the the lower and upper threshold in the funtion
Mat saltPepperNoise(Mat src);
#endif